# This file is AUTOMATICALLY GENERATED from the rgen package.
# DO NOT MANUALLY ALTER.
#
# Open Perimetry Interface implementation for Compass
#
# Copyright [2022] [Andrew Turpin & Ivan Marin-Franch]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require(rjson)

    # environment for this machine in R
if (exists(".opi_env") && !exists("Compass", where = .opi_env))
    assign("Compass", new.env(), envir = .opi_env)

#' Implementation of opiInitialise for the Compass machine.
#'
#' This is for internal use only. Use [opiInitialise()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{address} A list containing:
#'  * \code{port} TCP port of the OPI Monitor.
#'  * \code{ip} IP Address of the OPI Monitor.
#'
#' @return A list containing:
#'  * \code{res} List with all of the other fields described in @ReturnMsg except 'error'.
#'    - \code{res$prly} The y-coordinate of the PRL measured initialisation (pixels).
#'    - \code{res$onhx} The x-coordinate of the ONH measured initialisation (pixels).
#'    - \code{res$prlx} The x-coordinate of the PRL measured initialisation (pixels).
#'    - \code{res$msg} The success or error message.
#'    - \code{res$error} Error code '0' if all good, something else otherwise.
#'    - \code{res$onhy} The y-coordinate of the ONH measured initialisation (pixels).
#'    - \code{res$image} The captured IR image at initialisation (base64 encoded).
#'
#' @details 
#'
#' \code{port} can take on values in the range \code{[0, 65535]}.
#'
#' @examples
#' chooseOpi("Compass")
#' result <- opiInitialise(address = list(port = 50001, ip = "localhost"))
#'
#' @seealso [opiInitialise()]
#'
opiInitialise_for_Compass <- function(address) {
    if (!exists("socket", where = .opi_env$Compass))
        assign("socket", open_socket(address$ip, address$port), .opi_env$Compass)
    else
        return(list(error = 4, msg = "Socket connection to Monitor already exists. Perhaps not closed properly last time? Restart Monitor and R."))

    if (is.null(.opi_env$Compass$socket))
        return(list(error = 2, msg = sprintf("Cannot Cannot find a server at %s on port %s", address$ip, address$port)))

    if (is.null(address)) return(list(error = 0 , msg = "Nothing to do in opiInitialise."))

    msg <- list(port = address$port, ip = address$ip)
    msg <- c(list(command = "initialize"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$Compass$socket)

    res <- readLines(.opi_env$Compass$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    return(res)
}

#' Implementation of opiQueryDevice for the Compass machine.
#'
#' This is for internal use only. Use [opiQueryDevice()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{} A list containing:

#'
#' @return A list containing:
#'  * \code{res} List with all of the other fields described in @ReturnMsg except 'error'.
#'    - \code{res$msg} The error message or a structure with the following data.
#'    - \code{res$error} '0' if success, something else if error.
#'
#'
#'
#' @examples
#' chooseOpi("Compass")
#' result <- opiQueryDevice()
#'
#' @seealso [opiQueryDevice()]
#'
opiQueryDevice_for_Compass <- function() {
    if(!exists(".opi_env") || !exists("Compass", envir = .opi_env) || !("socket" %in% names(.opi_env$Compass)) || is.null(.opi_env$Compass$socket))
        return(list(error = 3, msg = "Cannot call opiQueryDevice without an open socket to Monitor. Did you call opiInitialise()?."))

    
    msg <- list()
    msg <- c(list(command = "query"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$Compass$socket)

    res <- readLines(.opi_env$Compass$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    return(res)
}

#' Implementation of opiSetup for the Compass machine.
#'
#' This is for internal use only. Use [opiSetup()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{settings} A list containing:
#'  * \code{fixShape} Fixation target type for eye. (Optional)
#'  * \code{fixCx} x-coordinate of fixation target (degrees): Only valid values
#'                 are -20, -6, -3, 0, 3, 6, 20 for fixation type 'spot' and -3,
#'                 0, 3 for fixation type 'square'. (Optional)
#'  * \code{tracking} Whether to correct stimulus location based on eye position. (Optional)
#'
#' @return A list containing:
#'  * \code{res} List with all of the other fields described in @ReturnMsg except 'error'.
#'    - \code{res$msg} The error message or a structure with the result of QUERY OPI command.
#'    - \code{res$error} '0' if success, something else if error.
#'
#' @details 
#'
#' \code{fixShape} can take on values in the set \code{{"spot", "square"}}.
#'
#' \code{fixCx} can take on values in the range \code{[-20.0, 20.0]}.
#'
#' \code{tracking} can take on values in the range \code{[0.0, 1.0]}.
#'
#' @examples
#' chooseOpi("Compass")
#' result <- opiSetup(settings = list())
#'
#' @seealso [opiSetup()]
#'
opiSetup_for_Compass <- function(settings) {
    if(!exists(".opi_env") || !exists("Compass", envir = .opi_env) || !("socket" %in% names(.opi_env$Compass)) || is.null(.opi_env$Compass$socket))
        return(list(error = 3, msg = "Cannot call opiSetup without an open socket to Monitor. Did you call opiInitialise()?."))

    if (is.null(settings)) return(list(error = 0 , msg = "Nothing to do in opiSetup."))

    msg <- list(fixShape = settings$fixShape, fixCx = settings$fixCx, tracking = settings$tracking)
    msg <- c(list(command = "setup"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$Compass$socket)

    res <- readLines(.opi_env$Compass$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    return(res)
}

#' Implementation of opiPresent for the Compass machine.
#'
#' This is for internal use only. Use [opiPresent()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{stim} A list containing:
#'  * \code{duration} Presentation time (ms).
#'  * \code{level} Stimuli luminance (cd/m^2).
#'  * \code{x} x co-ordinates of stimulus (degrees).
#'  * \code{y} y co-ordinates of stimulus (degrees).
#'  * \code{responseWindow} Response window (ms).
#'  * \code{stim.length} The number of elements in this stimuli.
#'
#' @return A list containing:
#'  * \code{res} JSON Object with all of the other fields described in @ReturnMsg except 'error'.
#'    - \code{res$eyet} Time of (eyex, eyey) pupil from stimulus onset (ms).
#'    - \code{res$eyex} x co-ordinates of pupil at times eyet (pixels).
#'    - \code{res$eyey} y co-ordinates of pupil at times eyet (pixels).
#'    - \code{res$num_track_events} Number of tracking events that occurred during presentation.
#'    - \code{res$msg$time} Response time from stimulus onset if button pressed (ms).
#'    - \code{res$eyed} Diameter of pupil at times eyet (mm).
#'    - \code{res$time_resp} Time since 'epoch' when stimulus response is
#'                           received, or response window expired (ms).
#'    - \code{res$msg} Error message or a structure with the following fields.
#'    - \code{res$error} '0' if success, something else if error.
#'    - \code{res$msg$seen} '1' if seen, '0' if not.
#'    - \code{res$num_motor_fails} Number of times motor could not follow fixation movement during presentation.
#'    - \code{res$time_rec} Time since 'epoch' when command was received at Compass or Maia (ms).
#'
#' @details 
#'
#' \code{duration} can take on values in the range \code{[200.0, 200.0]}.
#'
#' \code{level} can take on values in the range \code{[0.0, 3183.099]}.
#'
#' \code{x} can take on values in the range \code{[-30.0, 30.0]}.
#'
#' \code{y} can take on values in the range \code{[-30.0, 30.0]}.
#'
#' \code{responseWindow} can take on values in the range \code{[200.0, 2680.0]}.
#'
#' \code{stim.length} can take on values in the range \code{[1, 2147483647]}.
#'
#' @examples
#' chooseOpi("Compass")
#' result <- opiPresent(stim = list(duration = 200.0, level = 100.0, x = 0.0, y = 0.0,
#'                   responseWindow = 1500.0, stim.length = 1))
#'
#' @seealso [opiPresent()]
#'
opiPresent_for_Compass <- function(stim) {
    if(!exists(".opi_env") || !exists("Compass", envir = .opi_env) || !("socket" %in% names(.opi_env$Compass)) || is.null(.opi_env$Compass$socket))
        return(list(error = 3, msg = "Cannot call opiPresent without an open socket to Monitor. Did you call opiInitialise()?."))

    if (is.null(stim)) return(list(error = 0 , msg = "Nothing to do in opiPresent."))

    msg <- list(duration = stim$duration, level = stim$level, x = stim$x, y = stim$y, responseWindow = stim$responseWindow, stim.length = stim$stim.length)
    msg <- c(list(command = "present"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$Compass$socket)

    res <- readLines(.opi_env$Compass$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    return(res)
}

#' Implementation of opiClose for the Compass machine.
#'
#' This is for internal use only. Use [opiClose()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{} A list containing:

#'
#' @return A list containing:
#'  * \code{res} List of result elements.
#'    - \code{res$msg} The error message or additional results from the CLOSE command
#'    - \code{res$error} '0' if success, something else if error.
#'    - \code{res$time} The time stamp for fixation data
#'    - \code{res$x} The time stamp for fixation data
#'    - \code{res$y} The time stamp for fixation data
#'
#'
#'
#' @examples
#' chooseOpi("Compass")
#' result <- opiClose()
#'
#' @seealso [opiClose()]
#'
opiClose_for_Compass <- function() {
    if(!exists(".opi_env") || !exists("Compass", envir = .opi_env) || !("socket" %in% names(.opi_env$Compass)) || is.null(.opi_env$Compass$socket))
        return(list(error = 3, msg = "Cannot call opiClose without an open socket to Monitor. Did you call opiInitialise()?."))

    
    msg <- list()
    msg <- c(list(command = "close"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$Compass$socket)

    res <- readLines(.opi_env$Compass$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    return(res)
}

