# This file is AUTOMATICALLY GENERATED from the rgen package.
# DO NOT MANUALLY ALTER.
#
# Open Perimetry Interface implementation for O900
#
# Copyright [2022] [Andrew Turpin & Ivan Marin-Franch]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require(rjson)

    # environment for this machine in R
if (exists(".opi_env") && !exists("O900", where = .opi_env))
    assign("O900", new.env(), envir = .opi_env)

#' Implementation of opiInitialise for the O900 machine.
#'
#' This is for internal use only. Use [opiInitialise()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{address} A list containing:
#'  * \code{port} TCP port of the OPI Monitor.
#'  * \code{ip} IP Address of the OPI Monitor.
#'
#' @return A list containing:
#'  * \code{res} List with all of the other fields described in @ReturnMsg except 'error'.
#'  * \code{res.msg} The success or error message.
#'  * \code{res.error} Error code '0' if all good, something else otherwise.
#'
#' @details 
#'
#' \code{port} can take on values in the range \code{[0, 65535]}.
#'
#' @examples
#' chooseOpi("O900")
#' result <- opiInitialise(address = list(port = 50001, ip = "localhost"))
#'
#' @seealso [opiInitialise()]
#'
opiInitialise_for_O900 <- function(address) {
    if (!exists("socket", where = .opi_env$O900))
        assign("socket", open_socket(address$ip, address$port), .opi_env$O900)
    else
        return(list(error = 4, msg = "Socket connection to Monitor already exists. Perhaps not closed properly last time? Restart Monitor and R."))

    if (is.null(.opi_env$O900$socket))
        return(list(error = 2, msg = sprintf("Cannot Cannot find a server at %s on port %s", address$ip, address$port)))

    if (is.null(address)) return(list(error = 0 , msg = "Nothing to do in opiInitialise."))

    msg <- list(port = address$port, ip = address$ip)
    msg <- c(list(command = "initialize"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$O900$socket)

    res <- readLines(.opi_env$O900$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    if (res$error)
        res <- c(err = res$msg)
    else
        res <- c(list(err = NULL), res$msg)
    return(res)
}

#' Implementation of opiQueryDevice for the O900 machine.
#'
#' This is for internal use only. Use [opiQueryDevice()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{} A list containing:

#'
#' @return A list containing:
#'  * \code{res} List with all of the other fields described in @ReturnMsg except 'error'.
#'  * \code{res.msg} The error message or a structure with the following data.
#'  * \code{res.error} '0' if success, something else if error.
#'
#'
#'
#' @examples
#' chooseOpi("O900")
#' result <- opiQueryDevice()
#'
#' @seealso [opiQueryDevice()]
#'
opiQueryDevice_for_O900 <- function() {
    if(!exists(".opi_env") || !exists("O900", envir = .opi_env) || !("socket" %in% names(.opi_env$O900)) || is.null(.opi_env$O900$socket))
        return(list(error = 3, msg = "Cannot call opiQueryDevice without an open socket to Monitor. Did you call opiInitialise()?."))

    
    msg <- list()
    msg <- c(list(command = "query"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$O900$socket)

    res <- readLines(.opi_env$O900$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    if (res$error)
        res <- c(err = res$msg)
    else
        res <- c(list(err = NULL), res$msg)
    return(res)
}

#' Implementation of opiSetup for the O900 machine.
#'
#' This is for internal use only. Use [opiSetup()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{settings} A list containing:
#'  * \code{eye} Eye to set.
#'  * \code{fixShape} Fixation target.
#'  * \code{pres} Volume for auditory feedback when a stimulus is presented: 0 means no buzzer.
#'  * \code{resp} Volume for auditory feedback when observer presses the
#'                clicker: 0 means no buzzer.
#'  * \code{fixIntensity} Fixation intensity(from 0% to 100%).
#'  * \code{bgLum} Background luminance for eye.
#'  * \code{bgCol} Background color for eye.
#'
#' @return A list containing:
#'  * \code{res} List with all of the other fields described in @ReturnMsg except 'error'.
#'  * \code{res.msg} The error message or a structure with the result of QUERY OPI command.
#'  * \code{res.error} '0' if success, something else if error.
#'
#' @details 
#'
#' \code{eye} can take on values in the set \code{{"left", "right"}}.
#'
#' \code{fixShape} can take on values in the set \code{{"center",
#'           "cross", "ring"}}.
#'
#' \code{pres} can take on values in the range \code{[0.0, 3.0]}.
#'
#' \code{resp} can take on values in the range \code{[0.0, 3.0]}.
#'
#' \code{fixIntensity} can take on values in the range \code{[0.0, 100.0]}.
#'
#' \code{bgLum} can take on values in the set \code{{"bg_off", "bg_1",
#'        "bg_10", "bg_100"}}.
#'
#' \code{bgCol} can take on values in the set \code{{"white", "yellow"}}.
#'
#' @examples
#' chooseOpi("O900")
#' result <- opiSetup(settings = list(eye = "null", fixShape = "null", pres = 0.0, resp = 0.0,
#'                 fixIntensity = 50.0, bgLum = "null", bgCol = "null"))
#'
#' @seealso [opiSetup()]
#'
opiSetup_for_O900 <- function(settings) {
    if(!exists(".opi_env") || !exists("O900", envir = .opi_env) || !("socket" %in% names(.opi_env$O900)) || is.null(.opi_env$O900$socket))
        return(list(error = 3, msg = "Cannot call opiSetup without an open socket to Monitor. Did you call opiInitialise()?."))

    if (is.null(settings)) return(list(error = 0 , msg = "Nothing to do in opiSetup."))

    msg <- list(eye = settings$eye, fixShape = settings$fixShape, pres = settings$pres, resp = settings$resp, fixIntensity = settings$fixIntensity, bgLum = settings$bgLum, bgCol = settings$bgCol)
    msg <- c(list(command = "setup"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$O900$socket)

    res <- readLines(.opi_env$O900$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    if (res$error)
        res <- c(err = res$msg)
    else
        res <- c(list(err = NULL), res$msg)
    return(res)
}

#' Implementation of opiPresent for the O900 machine.
#'
#' This is for internal use only. Use [opiPresent()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{stim} A list containing:
#'  * \code{size} Stimulus size (degrees). Can be Goldmann Size I to V (or VI if
#'                device has a big wheel)
#'  * \code{color} Stimulus color (degrees).
#'  * \code{t} List of Stimulus presentation times (ms). For STATIC, list must
#'             be of length 1. For KINETIC, it must the same length and 'x' and
#'             'y' co-ordinates minus 1 (Optional)
#'  * \code{lum} List of stimuli luminances (cd/m^2).
#'  * \code{w} Response window for STATIC (ms). (Optional)
#'  * \code{x} List of x co-ordinates of stimuli (degrees).
#'  * \code{y} List of y co-ordinates of stimuli (degrees).
#'  * \code{type} Stimulus type: STATIC or KINETIC.
#'
#' @param \code{...} Parameters for other opiPresent implementations that are ignored here.
#'
#' @return A list containing:
#'  * \code{res} List with all of the other fields described in @ReturnMsg except 'error'.
#'  * \code{res.msg.eyey} y co-ordinates of pupil at times eyet (degrees).
#'  * \code{res.msg.eyex} x co-ordinates of pupil at times eyet (degrees).
#'  * \code{res.msg.time} Response time from stimulus onset if button pressed (ms).
#'  * \code{res.msg} Error message or a structure with the following fields.
#'  * \code{res.error} '0' if success, something else if error.
#'  * \code{res.msg.seen} '1' if seen, '0' if not.
#'  * \code{res.msg.x} x co-ordinate when oberver responded (degrees) for KINETIC.
#'  * \code{res.msg.y} y co-ordinate when oberver responded (degrees) for KINETIC.
#'
#' @details 
#'
#' \code{size} can take on values in the set \code{{"gi", "gii",
#'       "giii", "giv", "gv", "gvi"}}.
#'
#' \code{color} can take on values in the set \code{{"white", "red", "blue"}}.
#'
#' Elements in \code{t} can take on values in the range \code{[0.0, 1.0E10]}.
#'
#' \code{lum} can take on values in the range \code{[0.0, 3183.099]}.
#'
#' \code{w} can take on values in the range \code{[0.0, 1.0E10]}.
#'
#' Elements in \code{x} can take on values in the range \code{[-90.0, 90.0]}.
#'
#' Elements in \code{y} can take on values in the range \code{[-90.0, 90.0]}.
#'
#' \code{type} can take on values in the set \code{{"static", "kinetic"}}.
#'
#' @examples
#' chooseOpi("O900")
#' result <- opiPresent(stim = list(size = "GV", color = "null", lum = 3183.099, x = list(0.0),
#'                   y = list(0.0), type = "null"))
#'
#' @seealso [opiPresent()]
#'
opiPresent_for_O900 <- function(stim, ...) {
    if(!exists(".opi_env") || !exists("O900", envir = .opi_env) || !("socket" %in% names(.opi_env$O900)) || is.null(.opi_env$O900$socket))
        return(list(error = 3, msg = "Cannot call opiPresent without an open socket to Monitor. Did you call opiInitialise()?."))

    if (is.null(stim)) return(list(error = 0 , msg = "Nothing to do in opiPresent."))

    msg <- list(size = stim$size, color = stim$color, t = stim$t, lum = stim$lum, w = stim$w, x = stim$x, y = stim$y, type = stim$type)
    msg <- c(list(command = "present"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$O900$socket)

    res <- readLines(.opi_env$O900$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    if (res$error)
        res <- c(err = res$msg)
    else
        res <- c(list(err = NULL), res$msg)
    return(res)
}

#' Implementation of opiClose for the O900 machine.
#'
#' This is for internal use only. Use [opiClose()] with
#' these Arguments and you will get the Value back.
#'
#' @usage NULL
#'
#' @param \code{} A list containing:

#'
#' @return A list containing:
#'  * \code{res} List of result elements.
#'  * \code{res.msg} The error message or additional results from the CLOSE command
#'  * \code{res.error} '0' if success, something else if error.
#'
#'
#'
#' @examples
#' chooseOpi("O900")
#' result <- opiClose()
#'
#' @seealso [opiClose()]
#'
opiClose_for_O900 <- function() {
    if(!exists(".opi_env") || !exists("O900", envir = .opi_env) || !("socket" %in% names(.opi_env$O900)) || is.null(.opi_env$O900$socket))
        return(list(error = 3, msg = "Cannot call opiClose without an open socket to Monitor. Did you call opiInitialise()?."))

    
    msg <- list()
    msg <- c(list(command = "close"), msg)
    msg <- msg[!unlist(lapply(msg, is.null))]
    msg <- rjson::toJSON(msg)
    writeLines(msg, .opi_env$O900$socket)

    res <- readLines(.opi_env$O900$socket, n = 1)
    if (length(res) == 0)
        return(list(error = 5, msg = "Monitor server exists but a connection was not closed properly using opiClose() last time it was used. Restart Monitor."))
    res <- rjson::fromJSON(res)
    if (res$error)
        res <- c(err = res$msg)
    else
        res <- c(list(err = NULL), res$msg)
    return(res)
}

